matrix:
  include:
    - language: python
      script:
        - pytest
      install:
        - pip install boto3
    - language: node_js
      node_js:
        - node
      cache:
        directories:
          - node_modules
      install: npm install -g serverless
      script:
        - sls deploy function --function hello
    - language: java
