matrix:
  include:
    - language: python
      script: pytest
    - language: node_js
      node_js:
        - node
      cache:
        directories:
          - node_modules
      install: npm install -g serverless
      script:
        - sls deploy list functions
    - language: java
