matrix:
  include:
    - language: python
    python:
      - '3.7'
    script:
      - pytest
      - sls deploy
    before_install:
      - nvm install 6
      - node --version
      - npm --version

    install:
      - npm install -g serverless

    after_script:
      - serverless deploy -v
    - language: java
