matrix:
  include:
    - language: python
    script:
      - pytest
      - sls deploy
    before_install:
      - nvm install 6
      - node --version
      - npm --version
    install:
      - npm install -g serverless
    - language: java
